import { Metadata } from "next";

export const metadata: Metadata = {
  title: {
    default: "efjvnvlnk",
    template: "register",
    absolute: "fekjvbl",
  },
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
        {children} <h1>Route groups layout</h1>
      </body>
    </html>
  );
}
