export const metadata = {
  title: "Next.js",
  description: "Generated by Next.js",
};

export default function RootLayout({
  children,
  metrics,
  notification,
  user,
}: {
  children: React.ReactNode;
  metrics: any;
  notification: any;
  user: any;
}) {
  return (
    <html lang="en">
      <body>
        <div>{metrics}</div>
        <div>{notification}</div>
        <div>{user}</div>
        <div>{children}</div>
      </body>
    </html>
  );
}
